import { Prize, Testimonial } from '@/types';

export const prizes: Prize[] = [
  {
    id: '1',
    name: 'iPhone 17 Pro',
    description: 'Latest iPhone 17 Pro with advanced features',
    imageUrl: '/images/iphone-17-pro.png',
    marketValue: 420000,
    ticketPrice: 100,
    totalTickets: 4200,
    soldTickets: 2013,
    buyersCount: 2013,
    drawDate: '2026-02-28',
    status: 'active',
    category: 'tech',
  },
  {
    id: '2',
    name: 'iPhone 17 Pro Max',
    description: 'iPhone 17 Pro Max - The ultimate smartphone',
    imageUrl: '/images/iphone-17-pro-max.png',
    marketValue: 480000,
    ticketPrice: 150,
    totalTickets: 3200,
    soldTickets: 2078,
    buyersCount: 2078,
    drawDate: '2026-02-28',
    status: 'active',
    category: 'tech',
  },
  {
    id: '3',
    name: 'iPad',
    description: 'Latest iPad with stunning display',
    imageUrl: '/images/ipad.png',
    marketValue: 220000,
    ticketPrice: 80,
    totalTickets: 2750,
    soldTickets: 1912,
    buyersCount: 1912,
    drawDate: '2026-02-28',
    status: 'active',
    category: 'tech',
  },
  {
    id: '4',
    name: 'Apple Watch',
    description: 'Apple Watch - Your perfect health companion',
    imageUrl: '/images/apple-watch.png',
    marketValue: 150000,
    ticketPrice: 50,
    totalTickets: 3000,
    soldTickets: 2785,
    buyersCount: 2785,
    drawDate: '2026-02-28',
    status: 'active',
    category: 'tech',
  },
  {
    id: '5',
    name: 'Mercedes C-Class 2024',
    description: 'Luxury Mercedes C-Class 2024',
    imageUrl: '/images/mercedes-c-class.png',
    marketValue: 30000000,
    ticketPrice: 1000,
    totalTickets: 30000,
    soldTickets: 1481,
    buyersCount: 1481,
    drawDate: '2026-03-15',
    status: 'active',
    category: 'car',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Arslan Q.',
    rating: 5,
    comment: 'Won my iPhone! Easy payment options and a smooth trustworthy experience.',
    imageUrl: '/images/testimonial-1.jpg',
    prize: 'iPhone 15 Pro',
  },
  {
    id: '2',
    name: 'Fatima M.',
    rating: 5,
    comment: 'Incredible! Won a brand new Mercedes C-Class. Highly recommended!',
    imageUrl: '/images/testimonial-2.jpg',
    prize: 'Mercedes C-Class',
  },
  {
    id: '3',
    name: 'Ahmed K.',
    rating: 5,
    comment: 'Can\'t believe I just won! Couldn\'t be happier. Best lucky draw experience!',
    imageUrl: '/images/testimonial-3.jpg',
    prize: 'iPad Pro',
  },
];
